// <auto-generated />
namespace Dotnet_Project1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class m1lk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m1lk));
        
        string IMigrationMetadata.Id
        {
            get { return "202205031005437_m1lk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
